### ISSUE TITLE
如何获取关于qemu/spike的书

### ISSUE THREAD

**Issue by jiazhaorong** [plctlab/PLCT-Weekly#169]
hi，
我前端时间在spike里添加了用户自定义指令的支持，但目前spike不能满足我们的仿真需求，需要用到qemu，但我们对qemu了解不多，请问如何能够获取你们的相关书籍呢？

**Comment by lazyparser** [comment]
感谢关注，书我们一直说要写，但是还没写完。。。

不过我们就要开始开课了，从4月15日之后开始，欢迎关注知乎上的PLCT实验室专栏（plct-lab），后续每周大概会有一次线上的公开课和讨论班

**Comment by lazyparser** [comment]
已经纳入到 2022 的 PLCT Roadmap 中，欢迎关注后续的新书发布💪
