### ISSUE TITLE
HERBCEPTIONS请

### ISSUE THREAD

**Issue by tearosccebe** [plctlab/PLCT-Weekly#287]
C++异常处理淘汰了。现在流行herbceptions

https://www.bilibili.com/video/BV1gM4y1c7HE/

**Comment by lazyparser** [comment]
已经添加进入 2022 flag 全家桶：

https://github.com/plctlab/PLCT-Weekly/blob/master/PLCT-Roadmap-2022.md

**Comment by lazyparser** [comment]
感谢建议～ 期待年底回收～
