### ISSUE TITLE
PLCT 2022 许愿池计划（请把愿望评论在这里）

### ISSUE THREAD

**Issue by lazyparser** [plctlab/PLCT-Weekly#289]
https://github.com/plctlab/PLCT-Weekly/blob/master/Open-Wishlist-2022.md

**Comment by lazyparser** [comment]
华南理工赖老师许愿 PyChip 相关的项目（具体2022年目标待定）

**Comment by lazyparser** [comment]
#278 and #288

**Comment by lazyparser** [comment]
2021年未完成的 DynamoRIO 和 LuaJIT 自动滚动到2022

**Comment by luojia65** [comment]
许愿：2022年有更好的oreboot和rustsbi软件 :)

**Comment by alexfanqi** [comment]
一个小愿望：可否用riscv lab预编译python wheel，raspberry pi就有https://piwheels.org/ 以及 https://github.com/pypa/manylinux，对嵌入式设备应该就更友好了

**Comment by lazyparser** [comment]
> 一个小愿望：可否用riscv lab预编译python wheel，raspberry pi就有https://piwheels.org/ 以及 https://github.com/pypa/manylinux ，对嵌入式设备应该就更友好了，就是不确定有多少人用

这个小愿望甚至在2021年就可以实现？

如果有构建的脚本和环境要求说明的话，我试试？

**Comment by poemonsense** [comment]
愿望：2022年提高chisel/firrtl以及Verilator的运行速度，**降低内存开销**。16GB内存笔记本也能编香山（狗头

**Comment by sequencer** [comment]
> 2022年提高chisel/firrtl以及Verilator的运行速度，降低内存开销。
不慌 马上 Chisel 快20%

**Comment by lazyparser** [comment]
> 愿望：2022年提高chisel/firrtl以及Verilator的运行速度，**降低内存开销**。16GB内存笔记本也能编香山（狗头

没问题。甚至我已经有了一个 plan B 保底计划（给配一个32GB的笔记本 XD）

**Comment by alexfanqi** [comment]
> > 一个小愿望：可否用riscv lab预编译python wheel，raspberry pi就有https://piwheels.org/ 以及 https://github.com/pypa/manylinux ，对嵌入式设备应该就更友好了，就是不确定有多少人用
> 
> 这个小愿望甚至在2021年就可以实现？
> 
> 如果有构建的脚本和环境要求说明的话，我试试？

有哇，manylinux的仓库 https://github.com/pypa/manylinux 下就是docker的构建脚本，看上去稍微改改应该就能用。不过该如何定义manylinux20xx_riscv就得和python社区扯了

**Comment by Icenowy** [comment]
许愿：FPGA 优化的 RV64GC （最好 V）软核

**Comment by bigmagic123** [comment]
希望PLCT能出够写出关于讲解编译器gcc和qemu原理的书籍，通过实战来进行分析

**Comment by bigmagic123** [comment]
希望PLCT能够在riscv gcc上投入精力更好的支持RVV，同时能够支持p扩展和v扩展的自动向量化

**Comment by yulong-plct** [comment]
希望成为gcc的dalo。

**Comment by zifeihan** [comment]
新年目标/愿望:OpenJDK for RV32G 早日跑通Helloworld

**Comment by zifeihan** [comment]
> 新年目标/愿望:OpenJDK for RV32G 早日跑通Helloworld

早日跑通 JIT

**Comment by fanghuaqi** [comment]
- LLVM工具链全家桶版本
- GCC/LLVM上的P/V扩展自动向量化

**Comment by lazyparser** [comment]
感谢大家，已经添加进入 2022 flag 全家桶：

https://github.com/plctlab/PLCT-Weekly/blob/master/PLCT-Roadmap-2022.md

1年后来回收flag
