### ISSUE TITLE
有5*8h的全职工作，是否可以远程兼职？

### ISSUE THREAD

**Issue by bignumlock** [plctlab/PLCT-Weekly#329]
本人日常工作是全栈开发的，对基础的软硬件技术有很大的兴趣，所以想借机会深入的学习一些知识，并贡献一些自己的能力。

在LINUX操作系统方面，主要是用的比较多，但是系统运行原理方面也了解一些，还懂一些编译和汇编方面的知识

**Comment by lazyparser** [comment]
Hi @bignumlock 

如果是问TRSR系列岗位的话，是同时接受全职、实习、和兼职的。

兼职的话默认需要已经在 RISC-V 操作系统 领域或 Linux 发行版开源社区有姓名（做过贡献）。另外实习和兼职并不是固定按时间，而是按照外部可见产出物进行劳务费发放，幅度一般在 500～5000 之间。欢迎加入。

**Comment by pycj** [comment]
全职的话工作地点可以完全远程工作么？本人目前在成都，暂时不想去北京，杭州等地。。
