### ISSUE TITLE
TRSR005全职是否可以完全远程工作，目前不在北京等城市，且不想换城市

### ISSUE THREAD

**Issue by pycj** [plctlab/PLCT-Weekly#330]
本人有一些汇编和C的基础，英文能力过关，对操作系统及硬件有很大兴趣，想从事这个工作

**Comment by lazyparser** [comment]
可以。可以先进入社群看看大家如何工作，如果感兴趣可以从兼职开始做起。如果跟自己想的一样，再转为全职。
