### ISSUE TITLE
是否可以添加 The Aya Theorem Prover 到月报模板中？

### ISSUE THREAD

**Issue by imkiva** [plctlab/PLCT-Weekly#450]
即在 `YYYY-MM-DD.md` 中任意处添加以下内容

```diff
+## The Aya Theorem Prover
```

起因：Aya 小组将从 8 月起（即 `2022-09-01.md`）使用自动化工具实现月报自动生成并向本仓库提交 PR。为了精准地（指不伤害其他小组的内容）向模板文件中添加内容，我们需要一个显著的 marker 进行文本替换（例如 `sed`）。

**Comment by lazyparser** [comment]
可以呀，过几天我创建一下新的md文件。

**Comment by imkiva** [comment]
好耶！😆
