### ISSUE TITLE
Aya team logs since 60 days ago

### ISSUE THREAD

**Issue by ice1000** [plctlab/PLCT-Weekly#532]
Remains to be copied to 2022-12 report.

## Misc

+ Tagged 2 new alpha releases
+ Wrote the first tutorial: <https://www.aya-prover.org/guide/haskeller-tutorial.html>
  + Assumed Haskell knowledge for simplicity
+ The binary distribution now ships the standard library candidate
+ We have some very basic synthetic homotopy theory results and theorems about natural numbers!

## The Aya Theorem Prover

[Watch Aya Prover](https://github.com/aya-prover/aya-dev)

+ [v0.25](https://github.com/aya-prover/aya-dev/milestone/17) Fix some issues, define Susp of S¹ to S² [PR-747](https://github.com/aya-prover/aya-dev/pull/747) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.25](https://github.com/aya-prover/aya-dev/milestone/17) Issue 596 [PR-745](https://github.com/aya-prover/aya-dev/pull/745) opened by [HoshinoTented](https://api.github.com/users/HoshinoTented)
+ [v0.25](https://github.com/aya-prover/aya-dev/milestone/17) Improve many things [PR-744](https://github.com/aya-prover/aya-dev/pull/744) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.25](https://github.com/aya-prover/aya-dev/milestone/17) Really do support eta-expand paths [PR-739](https://github.com/aya-prover/aya-dev/pull/739) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.25](https://github.com/aya-prover/aya-dev/milestone/17) Small fixes. [PR-740](https://github.com/aya-prover/aya-dev/pull/740) opened by [wsx-ucb](https://api.github.com/users/wsx-ucb)
+ [v0.25](https://github.com/aya-prover/aya-dev/milestone/17) Implement coercion from path to pi [PR-738](https://github.com/aya-prover/aya-dev/pull/738) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.25](https://github.com/aya-prover/aya-dev/milestone/17) Install also the stdlib [PR-736](https://github.com/aya-prover/aya-dev/pull/736) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.25](https://github.com/aya-prover/aya-dev/milestone/17) basic support for unary pretty print [PR-735](https://github.com/aya-prover/aya-dev/pull/735) opened by [tsao-chi](https://api.github.com/users/tsao-chi)
+ [v0.25](https://github.com/aya-prover/aya-dev/milestone/17) Remove ulift [PR-734](https://github.com/aya-prover/aya-dev/pull/734) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.25](https://github.com/aya-prover/aya-dev/milestone/17) Clear Garbage Code of PatTycker [PR-732](https://github.com/aya-prover/aya-dev/pull/732) opened by [HoshinoTented](https://api.github.com/users/HoshinoTented)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Use the meaningful test data [PR-666](https://github.com/aya-prover/aya-dev/pull/666) opened by [HoshinoTented](https://api.github.com/users/HoshinoTented)
+ [v0.25](https://github.com/aya-prover/aya-dev/milestone/17) Improve library with pushing [PR-724](https://github.com/aya-prover/aya-dev/pull/724) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.25](https://github.com/aya-prover/aya-dev/milestone/17) Push telescope [PR-723](https://github.com/aya-prover/aya-dev/pull/723) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.25](https://github.com/aya-prover/aya-dev/milestone/17) cli: remove a duplicate checkDeserialization() call [PR-720](https://github.com/aya-prover/aya-dev/pull/720) opened by [tsao-chi](https://api.github.com/users/tsao-chi)
+ [v0.25](https://github.com/aya-prover/aya-dev/milestone/17) No Erase [PR-667](https://github.com/aya-prover/aya-dev/pull/667) opened by [tsao-chi](https://api.github.com/users/tsao-chi)
+ [v0.25](https://github.com/aya-prover/aya-dev/milestone/17) Add `*-comm`, `*-assoc` in library candidate [PR-722](https://github.com/aya-prover/aya-dev/pull/722) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Release 0.24 [PR-718](https://github.com/aya-prover/aya-dev/pull/718) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Fix Highlighter [PR-716](https://github.com/aya-prover/aya-dev/pull/716) opened by [HoshinoTented](https://api.github.com/users/HoshinoTented)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Desugar do-notation with correct source pos [PR-717](https://github.com/aya-prover/aya-dev/pull/717) opened by [imkiva](https://api.github.com/users/imkiva)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Fix SourcePos of Let [PR-715](https://github.com/aya-prover/aya-dev/pull/715) opened by [HoshinoTented](https://api.github.com/users/HoshinoTented)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Leafover of Let Expr [PR-712](https://github.com/aya-prover/aya-dev/pull/712) opened by [HoshinoTented](https://api.github.com/users/HoshinoTented)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Overhaul `loadFile` in REPL [PR-714](https://github.com/aya-prover/aya-dev/pull/714) opened by [imkiva](https://api.github.com/users/imkiva)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) bnf: make `LetBind` a named element [PR-713](https://github.com/aya-prover/aya-dev/pull/713) opened by [imkiva](https://api.github.com/users/imkiva)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Let Expression [PR-699](https://github.com/aya-prover/aya-dev/pull/699) opened by [HoshinoTented](https://api.github.com/users/HoshinoTented)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Slightly less code in parser [PR-711](https://github.com/aya-prover/aya-dev/pull/711) opened by [ice1000](https://api.github.com/users/ice1000)
+ Depreacte `StmtOps` and `ExprTraversal` [PR-709](https://github.com/aya-prover/aya-dev/pull/709) opened by [imkiva](https://api.github.com/users/imkiva)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Unify literate highlighter and LSP highlighter [PR-708](https://github.com/aya-prover/aya-dev/pull/708) opened by [imkiva](https://api.github.com/users/imkiva)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Interesting parser improvements [PR-707](https://github.com/aya-prover/aya-dev/pull/707) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Fix a bug: HIT partial forgot to zonk [PR-705](https://github.com/aya-prover/aya-dev/pull/705) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Highlighter with Linker [PR-698](https://github.com/aya-prover/aya-dev/pull/698) opened by [HoshinoTented](https://api.github.com/users/HoshinoTented)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) New `group` library config and polish some messages [PR-702](https://github.com/aya-prover/aya-dev/pull/702) opened by [imkiva](https://api.github.com/users/imkiva)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Luna's branch that tries to fix bug [PR-602](https://github.com/aya-prover/aya-dev/pull/602) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) REPL: decouple and fix [PR-701](https://github.com/aya-prover/aya-dev/pull/701) opened by [imkiva](https://api.github.com/users/imkiva)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Cherry pick from 'no more duplicated vars' [PR-703](https://github.com/aya-prover/aya-dev/pull/703) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Kiva fixing something today [PR-700](https://github.com/aya-prover/aya-dev/pull/700) opened by [imkiva](https://api.github.com/users/imkiva)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Rename java to jaya [PR-697](https://github.com/aya-prover/aya-dev/pull/697) opened by [ice1000](https://api.github.com/users/ice1000)
+ Add license scan report and status [PR-696](https://github.com/aya-prover/aya-dev/pull/696) opened by [fossabot](https://api.github.com/users/fossabot)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Try using `meta` rules [PR-695](https://github.com/aya-prover/aya-dev/pull/695) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) change: Change comment syntax (BREAKING CHANGE) [PR-678](https://github.com/aya-prover/aya-dev/pull/678) opened by [wsx-ucb](https://api.github.com/users/wsx-ucb)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Fix my opinions [PR-693](https://github.com/aya-prover/aya-dev/pull/693) opened by [imkiva](https://api.github.com/users/imkiva)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Minor improvements [PR-692](https://github.com/aya-prover/aya-dev/pull/692) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Report mising operand for unary sections [PR-688](https://github.com/aya-prover/aya-dev/pull/688) opened by [imkiva](https://api.github.com/users/imkiva)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Parse private decl [PR-689](https://github.com/aya-prover/aya-dev/pull/689) opened by [imkiva](https://api.github.com/users/imkiva)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Better `did you mean` messages [PR-675](https://github.com/aya-prover/aya-dev/pull/675) opened by [imkiva](https://api.github.com/users/imkiva)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Improve readme, disallow | from beginning of identifiers [PR-682](https://github.com/aya-prover/aya-dev/pull/682) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Natural number properties, naming convention, etc. [PR-681](https://github.com/aya-prover/aya-dev/pull/681) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) graal: generate part of the config [PR-673](https://github.com/aya-prover/aya-dev/pull/673) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) LSP: Search library root in dependencies [PR-674](https://github.com/aya-prover/aya-dev/pull/674) opened by [imkiva](https://api.github.com/users/imkiva)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Update library, define S², T³ [PR-671](https://github.com/aya-prover/aya-dev/pull/671) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Higher inductive types [PR-669](https://github.com/aya-prover/aya-dev/pull/669) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) KALA: upgrade to 0.56.0 [PR-668](https://github.com/aya-prover/aya-dev/pull/668) opened by [Glavo](https://api.github.com/users/Glavo)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Revert some changes [PR-664](https://github.com/aya-prover/aya-dev/pull/664) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Fix some code [PR-655](https://github.com/aya-prover/aya-dev/pull/655) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) More ShuYu [PR-661](https://github.com/aya-prover/aya-dev/pull/661) opened by [HoshinoTented](https://api.github.com/users/HoshinoTented)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Fix some bugs  [PR-660](https://github.com/aya-prover/aya-dev/pull/660) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Do Unifying Owner Telescope [PR-658](https://github.com/aya-prover/aya-dev/pull/658) opened by [HoshinoTented](https://api.github.com/users/HoshinoTented)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Fix tycking induction-recursion definitions [PR-659](https://github.com/aya-prover/aya-dev/pull/659) opened by [imkiva](https://api.github.com/users/imkiva)
+ [v0.24](https://github.com/aya-prover/aya-dev/milestone/16) Enhance #646 [PR-656](https://github.com/aya-prover/aya-dev/pull/656) opened by [HoshinoTented](https://api.github.com/users/HoshinoTented)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Release v0.23 [PR-654](https://github.com/aya-prover/aya-dev/pull/654) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Add some cli options [PR-653](https://github.com/aya-prover/aya-dev/pull/653) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Fix some LSP bugs [PR-652](https://github.com/aya-prover/aya-dev/pull/652) opened by [imkiva](https://api.github.com/users/imkiva)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) More Colorful Cli [PR-646](https://github.com/aya-prover/aya-dev/pull/646) opened by [HoshinoTented](https://api.github.com/users/HoshinoTented)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) NXJASbhjasbxjhsbxhjasbxhjasbxjas [PR-650](https://github.com/aya-prover/aya-dev/pull/650) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Sigma transport [PR-649](https://github.com/aya-prover/aya-dev/pull/649) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Allow connected ↑ [PR-648](https://github.com/aya-prover/aya-dev/pull/648) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Overhaul literal infrastructure [PR-641](https://github.com/aya-prover/aya-dev/pull/641) opened by [imkiva](https://api.github.com/users/imkiva)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Define `coeSigma4` and `coeSigma5`, upgrade guest with a smol optimization [PR-647](https://github.com/aya-prover/aya-dev/pull/647) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Trivial [PR-644](https://github.com/aya-prover/aya-dev/pull/644) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) sort: use single record instead of interface [PR-640](https://github.com/aya-prover/aya-dev/pull/640) opened by [tsao-chi](https://api.github.com/users/tsao-chi)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Delete `PatElem` [PR-643](https://github.com/aya-prover/aya-dev/pull/643) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) `Pattern` -> `Arg<Pattern>` [PR-642](https://github.com/aya-prover/aya-dev/pull/642) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Constant check for `coeFill`, `coeInv` and `coeInvFill` [PR-635](https://github.com/aya-prover/aya-dev/pull/635) opened by [imkiva](https://api.github.com/users/imkiva)
+ sort: use single record instead of interface [PR-639](https://github.com/aya-prover/aya-dev/pull/639) opened by [tsao-chi](https://api.github.com/users/tsao-chi)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Allowing Implicit Argument in List Ctor [PR-634](https://github.com/aya-prover/aya-dev/pull/634) opened by [HoshinoTented](https://api.github.com/users/HoshinoTented)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Disallow using `coe` as function [PR-633](https://github.com/aya-prover/aya-dev/pull/633) opened by [imkiva](https://api.github.com/users/imkiva)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Issue #598, Part 1. [PR-599](https://github.com/aya-prover/aya-dev/pull/599) opened by [HoshinoTented](https://api.github.com/users/HoshinoTented)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Massive rename planned long time ago [PR-632](https://github.com/aya-prover/aya-dev/pull/632) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Implement Prop pattern matching tyck [PR-629](https://github.com/aya-prover/aya-dev/pull/629) opened by [tsao-chi](https://api.github.com/users/tsao-chi)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Pat.Meta in Pat.Meta [PR-630](https://github.com/aya-prover/aya-dev/pull/630) opened by [HoshinoTented](https://api.github.com/users/HoshinoTented)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Don't normalize too early [PR-628](https://github.com/aya-prover/aya-dev/pull/628) opened by [HoshinoTented](https://api.github.com/users/HoshinoTented)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Doc: Add some docs for the refactor. [PR-627](https://github.com/aya-prover/aya-dev/pull/627) opened by [wsx-ucb](https://api.github.com/users/wsx-ucb)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Match expression [PR-545](https://github.com/aya-prover/aya-dev/pull/545) opened by [wsx-ucb](https://api.github.com/users/wsx-ucb)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Fix #625 [PR-626](https://github.com/aya-prover/aya-dev/pull/626) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Codifier: a new tool for writing helper functions internally [PR-624](https://github.com/aya-prover/aya-dev/pull/624) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) No more useless subst [PR-623](https://github.com/aya-prover/aya-dev/pull/623) opened by [HoshinoTented](https://api.github.com/users/HoshinoTented)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Purge `raiseError` [PR-622](https://github.com/aya-prover/aya-dev/pull/622) opened by [imkiva](https://api.github.com/users/imkiva)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Issue 620 [PR-621](https://github.com/aya-prover/aya-dev/pull/621) opened by [HoshinoTented](https://api.github.com/users/HoshinoTented)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Random changes, fix simple lsp bug [PR-619](https://github.com/aya-prover/aya-dev/pull/619) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Issue 609 [PR-610](https://github.com/aya-prover/aya-dev/pull/610) opened by [HoshinoTented](https://api.github.com/users/HoshinoTented)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Computation rule of coe for binary sigma type [PR-616](https://github.com/aya-prover/aya-dev/pull/616) opened by [lunalunaa](https://api.github.com/users/lunalunaa)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Cherry pick from @HoshinoTented's branch [PR-617](https://github.com/aya-prover/aya-dev/pull/617) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Upgrade (again, sorry!) [PR-615](https://github.com/aya-prover/aya-dev/pull/615) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) @wsx-ucb's code cherry pick [PR-614](https://github.com/aya-prover/aya-dev/pull/614) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Major tom [PR-612](https://github.com/aya-prover/aya-dev/pull/612) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Many build improvements [PR-611](https://github.com/aya-prover/aya-dev/pull/611) opened by [HoshinoTented](https://api.github.com/users/HoshinoTented)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Prop and Erased [PR-584](https://github.com/aya-prover/aya-dev/pull/584) opened by [tsao-chi](https://api.github.com/users/tsao-chi)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Fix: Issue 597 [PR-603](https://github.com/aya-prover/aya-dev/pull/603) opened by [HoshinoTented](https://api.github.com/users/HoshinoTented)
+ fix regression of #437 in #579 [PR-608](https://github.com/aya-prover/aya-dev/pull/608) opened by [imkiva](https://api.github.com/users/imkiva)
+ [v0.22](https://github.com/aya-prover/aya-dev/milestone/13) Do not stop literal classification that early [PR-579](https://github.com/aya-prover/aya-dev/pull/579) opened by [imkiva](https://api.github.com/users/imkiva)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) Overhaul the `Sub` system of unification [PR-606](https://github.com/aya-prover/aya-dev/pull/606) opened by [ice1000](https://api.github.com/users/ice1000)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) respect renamed operator in serialized bind [PR-605](https://github.com/aya-prover/aya-dev/pull/605) opened by [imkiva](https://api.github.com/users/imkiva)
+ [v0.23](https://github.com/aya-prover/aya-dev/milestone/15) transport and hcomp [PR-539](https://github.com/aya-prover/aya-dev/pull/539) opened by [lunalunaa](https://api.github.com/users/lunalunaa)

[Watch Aya Intellij Plugin](https://github.com/aya-prover/intellij-aya)

+ Update grammar [PR-29](https://github.com/aya-prover/intellij-aya/pull/29) opened by [imkiva](https://api.github.com/users/imkiva)
+ Update to aya 0.23 [PR-28](https://github.com/aya-prover/intellij-aya/pull/28) opened by [imkiva](https://api.github.com/users/imkiva)
+ IJ debugger [PR-20](https://github.com/aya-prover/intellij-aya/pull/20) opened by [imkiva](https://api.github.com/users/imkiva)
+ Update grammar [PR-26](https://github.com/aya-prover/intellij-aya/pull/26) opened by [HoshinoTented](https://api.github.com/users/HoshinoTented)
+ Reorganize classes [PR-24](https://github.com/aya-prover/intellij-aya/pull/24) opened by [imkiva](https://api.github.com/users/imkiva)
+ Update grammar to aya 0.22 [PR-21](https://github.com/aya-prover/intellij-aya/pull/21) opened by [imkiva](https://api.github.com/users/imkiva)

**Comment by lazyparser** [comment]
Ready to go

**Comment by ice1000** [comment]
🎸
